import os 
import time 
if os.geteuid() != 0:
    exit("You need to have root privileges to run this script.\nPlease try again, this time using 'sudo'. Exiting.")
input("please connect to internet via network cable, then press enter")
print("updating system")
os.system("apt update")
os.system("apt upgrade")
print("installing apt packages")
os.system("apt install alsa-utils")
os.system("apt install libespeak1")
os.system("apt install net-tools")
os.system("apt install python3-rpi.gpio")
os.system("apt install bpytop")
print("installing pip3 packages")
os.system("pip3 install wikipedia")
os.system("pip3 install datetime")
os.system("pip3 install speechRecognition")
os.system("pip3 install pyttsx3")
os.system("pip3 install gpiozero")
print("seting up start.service")
os.system("mv start.service /etc/systemd/system/start.service")
os.system("systemctl enable start")
print("wifi setup")
os.system("ifconfig wlan0 up")
print("scanning for networks")
os.system("ifconfig wlan0 up")
print(os.system("nmcli dev wifi"))
wifi = input("do you want to connect to wifi? (y/n)
if(wifi = "y"):
    netName = input("enter the name of the network you wish to connect to as it appears above: ")
    password = input("enter network password (leave blank if none): ")
    if(password == ""):
        os.system("iwconfig wlan0 essid "+netName)
    if(password != ""):
        os.system("iwconfig wlan0 essid "+netName+" key "+password)
    print("i haven't implemented network tests, so.....")
time.sleep(1)
print("restarting")
os.system("shutdown -r now")
